# Use postgres/example user/password credentials
services:

  db:
    image: postgres
    restart: always
    # set shared memory limit when using docker compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    volumes:
      - /run/desktop/mnt/host/c/Users/admin/Documents/DB/postgres:/var/lib/postgresql/data
    
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: Trd19afo

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
